### ISSUE TITLE
Suggestions for documenting/promoting the cv package

### ISSUE THREAD

**Issue by friendly** [gmonette/cv#2]
At the start of the README that becomes the landing  page `https://gmonette.github.io/cv/`, revise to give a better overview of what the package aims to do.

* Delete "Various functions..." in title, just: `cv package for R: Cross-Validation of Regression Models`
* Add an overview statement, something like

> The `cv` package aims to provide a consistent and extensible framework for cross-validation of regression models. It provides a generic function, `cv()` to handle a variety of model types and functions for model selection via cross-validation.
> Some of the functions supplied by the package:
...

**Comment by friendly** [comment]
Also, provide headings for examples/vignettes and installation. Something like

## Examples
* For additional information on using the cv package, see the “[Cross-validation of regression models](https://gmonette.github.io/cv/articles/cv.html)” vignette ([vignette("cv", package="cv")](https://gmonette.github.io/cv/articles/cv.html)). 
* The cv package is designed to be extensible to other classes of regression models and other model-selection procedures; for details, see the “[Extending the cv package](https://gmonette.github.io/cv/articles/cv-extend.html)” vignette ([vignette("cv-extend", package="cv")](https://gmonette.github.io/cv/articles/cv-extend.html)).

## Installation
To install the current version of the cv package from CRAN:

**Comment by john-d-fox** [comment]
Thanks Michael. I've updated the README more or less along the lines your suggested.
