### ISSUE TITLE
Comments on vignette

### ISSUE THREAD

**Issue by friendly** [gmonette/cv#5]
The main vignette for the package has now gotten much more detailed, but my sense is that it is overly long.

Perhaps the main vignette, that appears on the 'Get started' page of the pkgdown site should consist only of the first two sections, through "Examples"?

at the least, the section on mixed models could be a separate stand-alone vignette, as could the two sections on parallel computation and computational notes.

Just my 0.02

**Comment by john-d-fox** [comment]
That seems like a reasonable suggestion to me. Pending the introduction of new graphics functions, I'll think about dividing the cv vignette into a relatively brief introduction and perhaps several specific vignettes.

**Comment by john-d-fox** [comment]
Here's a proposal for reorganizing the main cv vignette, which is similar to Michael's suggestion:

Move the material on mixed models and CV of model selection to two separate vignettes; move the computational notes and the section in the extending-cv vignette on why the complement of the AUC isn't a casewise criterion to a separate vignette. 

Then the main cv vignette would retain not just the examples but also the brief sections on replicating CV, manipulating cv objects, and parallel computations.

If Michael comes up with new plotting methods, then they could go in a separate vignette along with the section on manipulating cv objects.

Thoughts?

**Comment by friendly** [comment]
My file `scratch/notes-michael/plot-test.R` now contains two small examples using car plotting methods that might be useful somewhere

**Comment by john-d-fox** [comment]
I've reorganized the vignettes along the lines I suggested; there are now 5 vignettes (see, e.g., the pkgdown site).

Michael: I looked at the graphs in `plot-test.R` and think that they need some more thought. For example, I don't think that it's sensible to use a nonparametric density estimate (as opposed, e.g., to a dot-plot) for 10 non-independent values. Maybe after the end of semester settles down, you, Georges, and I can discuss how to proceed with graphs.

**Comment by john-d-fox** [comment]
To elaborate slightly: There's a lot of information in `"cv"` and related objects. The plotting, printing, and summary methods that I wrote strike me as crude, but it's not obvious to me how to do it better. 

Michael's suggestion to create `as.data.frame()` methods was very helpful. The resulting objects can have rows pertaining to the product set of models, repetitions, and folds (or a subset of these three), and can contain columns for CV criteria and related quantities (such as their SEs) and for "coefficients" (broadly construed). 

What kinds of summaries and graphs are useful for presenting this information?

 I know that Michael is skilled in thinking about this kind of issue.
