### ISSUE TITLE
Problem with dynamic formula creation and selectStepAIC

### ISSUE THREAD

**Issue by ccasar** [gmonette/cv#6]
Hi,

I'm not sure if this is the right place to ask, but here is an example I am having trouble with when using the `cv` package and creating formulas dynamically :

```
library(cv)

data("Mroz", package = "carData")

do_stuff <- function(data){
  mform <- as.formula(paste0("inc ~ ", paste("k5", "k618", "age", sep =" + ")))
  m.mroz <- lm(formula = mform, data = Mroz)
  
  m.mroz.sel.cv <- cv(
    selectStepAIC,
    data,
    direction = "backward",
    working.model = m.mroz
  )
}


do_stuff(Mroz)
```

When running the do_stuff() function, I get this error:
`Error in eval(mf, parent.frame()) : object 'mform' not found`

And the traceback looks like this:

```
13: stats::model.frame(formula = mform, data = data[-indices, ], 
        drop.unused.levels = TRUE)
12: eval(mf, parent.frame())
11: eval(mf, parent.frame())
10: lm(formula = mform, data = data[-indices, ])
9: eval(call, parent.frame())
8: eval(call, parent.frame())
7: update.default(model, data = data[-indices, ])
6: update(model, data = data[-indices, ]) at cv-select.R#188
5: procedure(data, indices.i, details = k <= 10L, criterion = criterion, 
       model = model, ...) at cv-utilities.R#732
4: cvSelect(procedure = model, data = data, criterion = criterion, 
       criterion.name = deparse(substitute(criterion)), model = working.model, 
       y.expression = y.expression, k = k, confint = confint, level = level, 
       reps = reps, details = details, save.model = save.model, 
       seed = seed, ncores = ncores, ...) at cv-select.R#138
3: cv.function(selectStepAIC, data, direction = "backward", working.model = m.mroz) at cv.R#168
2: cv(selectStepAIC, data, direction = "backward", working.model = m.mroz) at #6
1: do_stuff(Mroz)
```

If I set an explicit formula like `inc ~ k5 + k618 + age` for the `lm()` call without creating it via `paste()` and `as.formula()`, there is no error.

There seems to be a problem with the visibility of `mform` while running `cv`, but I'm not sure how to fix this.

Do you have any suggestions?

**Comment by john-d-fox** [comment]
Thank you for providing a clear, minimal, reproducible example of the problem.

Without working out the details, the apparent issue is that R is lexically rather than dynamically scoped, so you need to put the formula where it can be found, such as the global environment. Here's a slightly modified version of your function that works (and that returns something rather than leaving the result in a local variable):
```
do_stuff <- function(data){
  assign("mform", 
         as.formula(paste0("inc ~ ", paste("k5", "k618", "age", sep =" + "))),
         envir=.GlobalEnv)
  m.mroz <- lm(formula = mform, data = Mroz)
  
  m.mroz.sel.cv <- cv(
    selectStepAIC,
    data,
    direction = "backward",
    working.model = m.mroz
  )
  m.mroz.sel.cv
}
```
which produces
```
> do_stuff(Mroz)
R RNG seed set to 807401
cross-validation criterion (mse) = 136.6309 
```
I hope that this helps.

**Comment by ccasar** [comment]
Thanks for the quick solution. I was aware of the interaction with the global environment, but not of the `assign()` function.

And yes, my example was a bit too minimal, the function in my real code returns some more meaningful result.

Thanks again!

**Comment by friendly** [comment]
An interesting example. @ccasar : Why did you want to put this in a function, since the formula was fixed?

I wonder whether `<<-` would have worked here rather than John's `assign()`

**Comment by ccasar** [comment]
In my real code the formula is pasted together from a dynamic number of variables that are supplied to the function, e.g. `as.formula(paste0("inc ~ ", paste(vector_of_variable_names, sep =" + ")))`. Here I just wanted to provide a simple, reproducible example.

And yes, `<<-`  also works. Totally forgot about that option.

**Comment by john-d-fox** [comment]
From `?"<<-"`:

> The operators `<<-` and `->>` are normally only used in functions, and cause a search to be made through parent environments for an existing definition of the variable being assigned. If such a variable is found (and its binding is not locked) then its value is redefined, otherwise assignment takes place in the global environment. 

So, yes, `<<-` is in this case equivalent to assigning the value in the global environment, but has the potential disadvantage of being unpredictable if a variable of the same name exists in an ancestor environment.
